#!/usr/bin/env python3
"""Generate docs/demo-report.md from data/processed/demo-result.json.

This is the future Cursor SDK bonus integration point: the plan
(docs/ai-usage.md) is to drive this report generation through a small Cursor
SDK automation so the AI-adaptation bonus is demonstrated with a real, useful
artifact instead of a gimmick. Until that wiring lands, this script produces
the same report deterministically so the demo never depends on the bonus.

TODO(cursor-sdk): wrap this generation in a Cursor SDK agent invocation and
document the exact command in README + docs/ai-usage.md.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULT_PATH = ROOT / "data" / "processed" / "demo-result.json"
REPORT_PATH = ROOT / "docs" / "demo-report.md"


def main() -> int:
    if not RESULT_PATH.exists():
        print(
            f"[demo-report] {RESULT_PATH.relative_to(ROOT)} not found — "
            "run scripts/demo-fixture.sh first",
            file=sys.stderr,
        )
        return 1

    result = json.loads(RESULT_PATH.read_text(encoding="utf-8"))

    images = result.get("results", [])
    all_detections = [d for img in images for d in img.get("detections", [])]
    class_counts = Counter(d["object_class"] for d in all_detections)
    faces_masked = sum(img["anonymization"]["faces_masked"] for img in images)
    plates_masked = sum(img["anonymization"]["plates_masked"] for img in images)
    warnings = list(result.get("warnings", []))
    for img in images:
        warnings.extend(img.get("warnings", []))

    lines = [
        "# Demo Report — Urban Object Inventory",
        "",
        "> Generated by `scripts/generate-demo-report.py` from "
        "`data/processed/demo-result.json`.",
        "> This file is gitignored; regenerate with `scripts/demo-fixture.sh` "
        "followed by `python3 scripts/generate-demo-report.py`.",
        "",
        f"- Demo run: `{result.get('demo_run_id', 'unknown')}` "
        f"({result.get('mode', 'unknown')} mode)",
        f"- Detection model: `{result.get('model', 'unknown')}`",
        f"- Images processed: **{len(images)}**",
        f"- Detections: **{len(all_detections)}**",
        "",
        "## KVKK anonymization gate",
        "",
        f"- Faces irreversibly masked: **{faces_masked}**",
        f"- License plates irreversibly masked: **{plates_masked}**",
        "- Method: see `anonymization.method` per image — counts only, no "
        "region contents are ever stored.",
        "",
        "## Detections by class",
        "",
        "| Object class | Count |",
        "| --- | --- |",
    ]
    for object_class, count in sorted(class_counts.items()):
        lines.append(f"| {object_class} | {count} |")
    if not class_counts:
        lines.append("| (none) | 0 |")

    lines += ["", "## Warnings", ""]
    if warnings:
        lines += [f"- {w}" for w in warnings]
    else:
        lines.append("- none")
    lines.append("")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"[demo-report] wrote {REPORT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
